name: deep-learning-with-python

dependencies:
- python=3.6
- scikit-learn
- scipy
- numpy
- matplotlib
- ipython
- jupyter
- pillow
- opencv
- graphviz
- cython
- pip:
  - tensorflow
  - keras
  - pydot-ng
